src/Entity/Pago.php
<?php

namespace App\Entity;

use App\Repository\PagoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PagoRepository::class)]
class Pago
{
    public const PAYMENT_TYPE_UNSPECIFIED = 0;
    public const PAYMENT_TYPE_CASH = 1;
    public const PAYMENT_TYPE_TRANSFER = 2;
    public const PAYMENT_TYPE_MERCADOPAGO = 3;

    public static $tipo_pagos = [
        self::PAYMENT_TYPE_UNSPECIFIED => 'No especificado',
        self::PAYMENT_TYPE_CASH => 'Efectivo',
        self::PAYMENT_TYPE_TRANSFER => 'Transferencia',
        self::PAYMENT_TYPE_MERCADOPAGO => 'MercadoPago',
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $monto = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha = null;

    #[ORM\Column]
    private ?int $tipo = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $observacion = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $numero_comprobante = null;

    #[ORM\Column]
    private ?int $importe_recibido = null;

    #[ORM\ManyToOne(inversedBy: 'pagos')]
    private ?Reserva $reserva = null;

    #[ORM\ManyToOne(inversedBy: 'pagos')]
    private ?User $user = null;

    public function __construct()
    {
        $this->fecha = new \DateTime();
        $this->setTipo(self::PAYMENT_TYPE_MERCADOPAGO);
    }

    public function __toString()
    {
        return (string)$this->id;
    }

    public static function getTipoPagoChoices() {
        return array_flip(self::$tipo_pagos);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMonto(): ?int
    {
        return $this->monto;
    }

    public function setMonto(int $monto): static
    {
        $this->monto = $monto;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): static
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getTipo(): ?int
    {
        return $this->tipo;
    }

    public function setTipo(int $tipo): static
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function getObservacion(): ?string
    {
        return $this->observacion;
    }

    public function setObservacion(?string $observacion): static
    {
        $this->observacion = $observacion;

        return $this;
    }

    public function getNumeroComprobante(): ?string
    {
        return $this->numero_comprobante;
    }

    public function setNumeroComprobante(?string $numero_comprobante): static
    {
        $this->numero_comprobante = $numero_comprobante;

        return $this;
    }

    public function getImporteRecibido(): ?int
    {
        return $this->importe_recibido;
    }

    public function setImporteRecibido(int $importe_recibido): static
    {
        $this->importe_recibido = $importe_recibido;

        return $this;
    }

    public function getReserva(): ?Reserva
    {
        return $this->reserva;
    }

    public function setReserva(?Reserva $reserva): static
    {
        $this->reserva = $reserva;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/ViajeAdminController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use Sonata\AdminBundle\Controller\CRUDController;
use Symfony\Component\Routing\Attribute\Route;

final class ViajeAdminController extends CRUDController
{
    public function asientosAction()
    {
        $asientos = $this->admin->getSubject()->getPasajes();

        return $this->render('ViajeAdmin/asientos.html.twig', [
            'controller_name' => 'ViajeAdminController',
            'asientos' => $asientos,
        ]);
    }
    public function ocuparAsientoAction()
    {
        $asientos = $this->admin->getSubject()->getPasajes();

        return $this->render('ViajeAdmin/ocuparAsiento.html.twig', [
            'controller_name' => 'ViajeAdminController',
            'asientos' => $asientos,
            'viajeid'    => $this->admin->getSubject()->getId()
        ]);
    }
}

templates/ViajeAdmin/asientos.html.twig
{% extends '@SonataAdmin/standard_layout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
    <style>
        .asientos-row {
            display: flex; /* Asegura que sea un contenedor flexbox */
            flex-wrap: nowrap; /* Evita el ajuste de línea */
        }

        .col-sm-1 {
            width: 4%;
        }
        .seat-button {
            width: 25px;
            height: 25px;
            border: 1px solid #ccc;
            margin: 5px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 14px;
            cursor: pointer;
            background-color: #eee; /* Color por defecto */
        }

        .seat-button-ocupado {
            width: 25px;
            height: 25px;
            border: 1px solid #ccc;
            margin: 5px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 14px;
            cursor: pointer;
            background-color: #0d6efd; /* Color por defecto */
        }

        .seat-button-disabled {
            width: 25px;
            height: 25px;
            border: 1px solid #ccc;
            margin: 5px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 14px;
            cursor: pointer;
            background-color: #ce8483; /* Color por defecto */
        }

        .seat-button.selected {
            background-color: darkgreen; /* Color cuando está seleccionado */
            color: white;
        }

        .pasillo-lateral {
            width: 10px; /* Ajusta el ancho del pasillo lateral */
            display: inline-block;
        }

        .pasillo-central {
            width: 30px; /* Ajusta el ancho del pasillo central */
            display: inline-block;
        }
    </style>
{% endblock %}
{% set css = {1:'seat-button-disabled', 0:'seat-button', 2:'seat-button-ocupado'} %}
{% set e = {1:'disabled', 0:'', 2:'disabled'} %}
{% set totalAsientos = 38 %}
{% set asientosPorFila = 3 %}
{% set filasPorSeccion = 10 %}
{% block sonata_admin_content %}

        <div class="col col-md-2 asientos-row">
            <div class="box box-solid box-primary">
                <div class="box-header  text-center">
                    <div class="box-title">Planta Baja</div>
                </div>
                <div class="container">
                    <div class="row flex asientos-row">
                     {% for asientoNumero in asientos %}
                        {% set fila = ((asientoNumero.asientoColectivo.asiento.numero - 1) / asientosPorFila)|round(0, 'ceil') %}
                        {% set asientoEnFila = (asientoNumero.asientoColectivo.asiento.numero - 1) % asientosPorFila + 1 %}

                        <div class="col">
                            <button type="button"
                                    class="{{ css[asientoNumero.estado] }}"
                                    data-asiento-id="{{ asientoNumero.asientoColectivo.asiento.id }}"
                                    data-pasaje-id="{{ asientoNumero.id }}"
                                    data-costo="{{ asientoNumero.costo }}"
                                    onclick="toggleAsiento(this)"
                                    {{ e[asientoNumero.estado] }}>
                                {{ asientoNumero.asientoColectivo.asiento.numero }}
                            </button>
                        </div>
                        {# Espacio después de cada fila de asientos #}
                        {% if asientoEnFila == asientosPorFila %}
                            </div>
                            {% if asientoNumero.asientoColectivo.asiento.numero == 12 %}
                            {% set asientosPorFila = 4 %}
                            </div>
                            </div>
                            </div>
                            <div class="col col-md-2 asientos-row">
                                <div class="box box-solid box-primary">
                                    <div class="box-header  text-center">
                                        <div class="box-title">Planta Alta</div>
                                    </div>
                                    <div class="container">
                                        <div class="row flex asientos-row">
                            {% else %}
                                <div class="row flex asientos-row">
                            {% endif%}
                        {% endif %}

                        {% if asientoEnFila == 2 %}
                            <div class="col-md-1"></div>
                        {% endif %}

                        {# Pasillo cada 'filasPorSeccion' filas #}
                        {% if asientoNumero.asientoColectivo.asiento.numero % (asientosPorFila * filasPorSeccion) == 0 %}
                            <div class="pasillo"></div><br>
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
        </div>
        </div>

                <div class="col col-md-2">
                    <div class="box box-solid box-primary">
                        <div class="box-header  text-center">
                            <div class="box-title">Asientos seleccionados:</div>
                        </div>
                        <div id="selectedAsientos">
                            Ningún asiento seleccionado.
                        </div>
                    </div>
                </div>

    <div class="modal fade" id="modalpago" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createModalLabel"><i class="ti-marker-alt m-r-10"></i></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="pago"></div>
            </div>
        </div>
    </div>
    {{ parent() }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

    <script type="text/javascript">
        let selectedAsientos = []; // Array para guardar los IDs de los asientos seleccionados

        function toggleAsiento(button) {
            const asientoId = button.dataset.asientoId;
            const pasajeId = button.dataset.pasajeId;
            const asientoCosto = button.dataset.costo;

            if (button.classList.contains('ocupado')) {
                return; // No hacer nada si el asiento está ocupado
            }

            button.classList.toggle('selected');

            const isSelected = button.classList.contains('selected');

            if (isSelected) {
                selectedAsientos.push({ id: asientoId, costo: asientoCosto, pid: pasajeId }); // Agrega el ID al array
            } else {
                selectedAsientos = selectedAsientos.filter(item => item.id !== asientoId); // Filtra por ID
            }
            updateSelectedAsientosDiv();
        }


        function updateSelectedAsientosDiv() {
            let total = 0;
            if (selectedAsientos.length === 0) {
                $('#selectedAsientos').html('Ningún asiento seleccionado.');
            } else {
                let totalCosto = 0;
                selectedAsientos.forEach(asiento => {
                    totalCosto += parseFloat(asiento.costo); // Convierte a número antes de sumar
                });

                // Construye la tabla HTML
                let tableHTML = '<table class="table table-bordered">';
                tableHTML += '<thead><tr><th>Asiento</th><th>Costo</th></tr></thead>';
                tableHTML += '<tbody>';

                selectedAsientos.forEach(asiento => {
                    tableHTML += `<tr><td>${asiento.id}</td><td>${asiento.costo}</td></tr>`;
                });

                // Agrega la fila del total
                tableHTML += `<tr><td><b>Total</b></td><td><b>$${totalCosto.toFixed(2)}</b></td></tr>`; // Formatea a 2 decimales

                tableHTML += `<tr><td colspan="2"><button id="enviarAsientos" data-toggle="modal" data-target="#modalpago"  class="btn btn-primary open-modal-form">Pagar</button></td></tr>`;
                tableHTML += '</tbody></table>';


                $('#selectedAsientos').html(tableHTML);

                $('#enviarAsientos').click(function() {
                    // Realiza la petición AJAX
                    $.ajax({
                        url: '{{ path('admin_app_pago_asientos') }}',
                        method: 'POST',
                        contentType: "application/json",
                        dataType: "html",
                        data: JSON.stringify(selectedAsientos),
                        success: function (data) {
                            $('#pago').html(data);
                            console.log(data);
                        },
                        error: function(xhr, status, error) {
                            console.error('Error al enviar los asientos:', error);
                            alert('Error al enviar los asientos.  Consulta la consola para más detalles.');
                        }
                    });
                });
            }
        }
    </script>
{% endblock %}

templates/ViajeAdmin/modal.html.twig
{% include 'modal.html.twig' %}
{% block sonata_admin %}
    <div class="modal-body">
        {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.monto) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.fecha) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.tipo) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.numeroComprobante) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.importeRecibido) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.pasajes) }}
                </div>
            </div>
        {{ form_end(form) }}
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Crear</button>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Inicializa Select2 (si lo usas)
            $('select').select2({ theme: 'bootstrap-5' });

            // Inicializa la colección de Sonata Admin (si es necesario)
            if (typeof sonata !== 'undefined' && typeof sonata.admin !== 'undefined') {
                sonata.admin.activateCollections();
            }
        });
    </script>
{% endblock %}

templates/ViajeAdmin/ocupar.html.twig
<a href="{{ path('admin_app_viaje_ocuparAsiento', {'id': object.id}) }}" class="btn btn-sm btn-success view_link" title="{{ 'Listado de Pasajes'|trans({}, 'SonataAdminBundle') }}" >
    <i class="fas fa-list-alt"></i>
    Ocupar
</a>

templates/ViajeAdmin/ocuparAsiento.html.twig
{% extends '@SonataAdmin/standard_layout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
    <style>
        .asientos-row {
            display: flex; /* Asegura que sea un contenedor flexbox */
            flex-wrap: nowrap; /* Evita el ajuste de línea */
        }

        .col-sm-1 {
            width: 4%;
        }

        .seat-button-ocupado {
            width: 25px;
            height: 25px;
            border: 1px solid #ccc;
            margin: 5px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 14px;
            cursor: pointer;
            background-color: #0d6efd; /* Color por defecto */
        }

        .seat-button {
            width: 25px;
            height: 25px;
            border: 1px solid #ccc;
            margin: 5px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 14px;
            cursor: pointer;
            background-color: #eee; /* Color por defecto */
        }

        .seat-button-disabled {
            width: 25px;
            height: 25px;
            border: 1px solid #ccc;
            margin: 5px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 14px;
            cursor: pointer;
            background-color: #ce8483; /* Color por defecto */
        }

        .seat-button.selected {
            background-color: darkgreen; /* Color cuando está seleccionado */
            color: white;
        }

        .pasillo-lateral {
            width: 10px; /* Ajusta el ancho del pasillo lateral */
            display: inline-block;
        }

        .pasillo-central {
            width: 30px; /* Ajusta el ancho del pasillo central */
            display: inline-block;
        }
    </style>
{% endblock %}
{% set css = {1:'seat-button-disabled', 0:'seat-button', 2:'seat-button-ocupado'} %}
{% set e = {1:'', 0:'disabled', 2:'disabled'} %}
{% set totalAsientos = 38 %}
{% set asientosPorFila = 3 %}
{% set filasPorSeccion = 10 %}
{% block sonata_admin_content %}


        <div class="col col-md-2 asientos-row">
            <div class="box box-solid box-primary">
                <div class="box-header  text-center">
                    <div class="box-title">Planta Baja</div>
                </div>
                <div class="container">
                    <div class="row flex asientos-row">
                     {% for asientoNumero in asientos %}
                        {% set fila = ((asientoNumero.asientoColectivo.asiento.numero - 1) / asientosPorFila)|round(0, 'ceil') %}
                        {% set asientoEnFila = (asientoNumero.asientoColectivo.asiento.numero - 1) % asientosPorFila + 1 %}

                        <div class="col">
                            <button type="button"
                                    class="{{ css[asientoNumero.estado] }}"
                                    data-asiento-id="{{ asientoNumero.asientoColectivo.asiento.id }}"
                                    data-pasaje-id="{{ asientoNumero.id }}"
                                    data-viaje-id="{{ viajeid }}"
                                    data-costo="{{ asientoNumero.costo }}"
                                    data-toggle="modal"
                                    data-target="#modalocupar"
                                    onclick="toggleAsiento(this)"
                                    {{ e[asientoNumero.estado] }}>
                                {{ asientoNumero.asientoColectivo.asiento.numero }}
                            </button>
                        </div>
                        {# Espacio después de cada fila de asientos #}
                        {% if asientoEnFila == asientosPorFila %}
                            </div>
                            {% if asientoNumero.asientoColectivo.asiento.numero == 12 %}
                            {% set asientosPorFila = 4 %}
                            </div>
                            </div>
                            </div>
                            <div class="col col-md-2 asientos-row">
                                <div class="box box-solid box-primary">
                                    <div class="box-header  text-center">
                                        <div class="box-title">Planta Alta</div>
                                    </div>
                                    <div class="container">
                                        <div class="row flex asientos-row">
                            {% else %}
                                <div class="row flex asientos-row">
                            {% endif%}
                        {% endif %}

                        {% if asientoEnFila == 2 %}
                            <div class="col-md-1"></div>
                        {% endif %}

                        {# Pasillo cada 'filasPorSeccion' filas #}
                        {% if asientoNumero.asientoColectivo.asiento.numero % (asientosPorFila * filasPorSeccion) == 0 %}
                            <div class="pasillo"></div><br>
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
        </div>
        </div>

    <div class="modal fade" id="modalocupar" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createModalLabel"><i class="ti-marker-alt m-r-10"></i></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="ocupar"></div>
            </div>
        </div>
    </div>
    {{ parent() }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
                function toggleAsiento(button) {
                const pasajeId = button.dataset.pasajeId;
                const viajeId = button.dataset.viajeId;
                    $.ajax({
                        url: '{{ path('admin_app_pago_ocuparAsiento') }}',
                        method: 'POST',
                        contentType: "application/json",
                        dataType: "json",
                        data: JSON.stringify({ 'idpasaje' : pasajeId, 'idviaje' : viajeId }),
                        success: function (data) {
                            $('#ocupar').html(data);
                            console.log(data);
                        },
                        error: function(xhr, status, error) {
                            console.error('Error al enviar asiento:', error);
                            alert('Error al enviar el asientos.  Consulta con el Administrador.');
                        }
                    });
                }
    </script>
{% endblock %}

templates/ViajeAdmin/pasaje.html.twig
<a href="{{ path('admin_app_viaje_asientos', {'id': object.id}) }}" class="btn btn-sm btn-primary view_link" title="{{ 'Listado de Pasajes'|trans({}, 'SonataAdminBundle') }}" >
    <i class="fas fa-list-alt"></i>
    Pasajes
</a>