src/Entity/Transporte.php
<?php

namespace App\Entity;

use App\Repository\TransporteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TransporteRepository::class)]
class Transporte
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 128)]
    private ?string $nombre = null;

    /**
     * @var Collection<int, TransporteAsiento>
     */
    #[ORM\OneToMany(targetEntity: TransporteAsiento::class, mappedBy: 'transporte', orphanRemoval: true, cascade: ["persist"])]
    #[ORM\OrderBy(["numero" => 'ASC'])]
    private Collection $asientos;

    #[ORM\Column(nullable: true)]
    private ?int $grilla_rows = null;

    #[ORM\Column(nullable: true)]
    private ?int $grilla_cols = null;

    #[ORM\Column(nullable: true)]
    private ?int $plantas = null;


    public static $planta_choices = [
        0 => 'Planta Baja',
        1 => 'Planta Alta',
    ];

    public function getPlantaLabel($planta){
        return self::$planta_choices[$planta];
    }

    public function __construct()
    {
        $this->asientos = new ArrayCollection();
    }

    public function __toString()
    {
        return ''.$this->nombre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * @return Collection<int, TransporteAsiento>
     */
    public function getAsientos(): Collection
    {
        return $this->asientos;
    }

    public function addAsiento(TransporteAsiento $asiento): static
    {
        if (!$this->asientos->contains($asiento)) {
            $this->asientos->add($asiento);
            $asiento->setTransporte($this);
        }

        return $this;
    }

    public function removeAsiento(TransporteAsiento $asiento): static
    {
        if ($this->asientos->removeElement($asiento)) {
            // set the owning side to null (unless already changed)
            if ($asiento->getTransporte() === $this) {
                $asiento->setTransporte(null);
            }
        }

        return $this;
    }

    public function getGrillaRows(): ?int
    {
        return $this->grilla_rows;
    }

    public function setGrillaRows(?int $grilla_rows): static
    {
        $this->grilla_rows = $grilla_rows;

        return $this;
    }

    public function getGrillaCols(): ?int
    {
        return $this->grilla_cols;
    }

    public function setGrillaCols(?int $grilla_cols): static
    {
        $this->grilla_cols = $grilla_cols;

        return $this;
    }

    public function getAsientoEnGrilla($planta, $row, $col) {
        $rs = $this->getAsientos()->matching(
            TransporteRepository::createGridPositionCriteria($planta, $row, $col)
        );
        $asiento = null;
        if(!$rs->isEmpty()) {
            $asiento = $rs->first();
        }
        return $asiento;
    }

    public function getPlantas(): ?int
    {
        return $this->plantas;
    }

    public function setPlantas(?int $plantas): static
    {
        $this->plantas = $plantas;

        return $this;
    }
}

src/Form/EventSubscriber/AddCiudadFieldSubscriber.php
<?php
namespace App\Form\EventSubscriber;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

use App\Entity\Ciudad;


class AddCiudadFieldSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        // Tells the dispatcher that you want to listen on the form.pre_set_data
        // event and that the preSetData method should be called.
        return [
            FormEvents::PRE_SET_DATA => 'preSetData',
            FormEvents::PRE_SUBMIT    => 'preSubmit'
        ];
    }

    private function addCityForm($form, $province_id)
    {
        $formOptions = array(
            'class'         => Ciudad::class,
            'empty_value'   => 'Ciudad',
            'label'         => 'Ciudad',
            'attr'          => array(
                'class' => 'city_selector',
            ),
            'query_builder' => function (EntityRepository $repository) use ($province_id) {
                $qb = $repository->createQueryBuilder('city')
                ->innerJoin('city.provincia', 'p')
                ->where('p.id = :provincia')
                ->setParameter('provincia', $province_id)
                ;

                return $qb;
            }
        );

        $form->add($this->propertyPathToCity, 'entity', $formOptions);
    }

    public function preSetData(FormEvent $event): void
    {
        $data = $event->getData();
        $form = $event->getForm();

        if (null === $data) {
            return;
        }

        $accessor    = PropertyAccess::createPropertyAccessor();
        $property_path_to_city = 'ciudad';
        #$form_options = $form->getConfig()->getOptions)();
        $city        = $accessor->getValue($data, $property_path_to_city);
        $province_id = ($city) ? $city->getProvince()->getId() : null;

        $this->addCityForm($form, $province_id);
    }
}

src/Form/EventSubscriber/AddDependantEntityFieldSubscriber.php
<?php
namespace App\Form\EventSubscriber;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;

use App\Entity\Ciudad;
use App\Entity\Provincia;
use App\Form\Type\DependantEntityType;
use App\Configuration\DependantEntityConfig;


class AddDependantEntityFieldSubscriber implements EventSubscriberInterface
{
    protected $property_accessor;
    protected $form_options;
    protected $fields;

    public function __construct()
    {
        $this->propertyAccessor = PropertyAccess::createPropertyAccessor();
        $this->form_options = null;
        $this->fields = array();
    }

    public function addField($name, $options) {
        $this->fields[$name] = $options;
    }

    public static function getSubscribedEvents(): array
    {
        // Tells the dispatcher that you want to listen on the form.pre_set_data
        // event and that the preSetData method should be called.
        return [
            FormEvents::PRE_SET_DATA => 'preSetData',
            FormEvents::PRE_SUBMIT   => 'preSubmit'
        ];
    }

    public function preSetData(FormEvent $event)
    {
        $data = $event->getData();
        $form = $event->getForm();

        if (null === $data) {
            return;
        }

        $accessor = $this->propertyAccessor;
        foreach($this->fields as $name => $options_original) {
            $options = array_merge([], $options_original);
            $object = $data;

            $obj_parent_field = $options['parent_entity_field'];

            if(isset($options['parent_form_field'])) {
                $obj_parent_field = $options['parent_form_field'];
            }
            $parent = ($object) ? $accessor->getValue($object, $obj_parent_field): null;
            $parent_id = ($parent)? $parent->getId() : null;

            $obj_field_name = $options['entity_field'];
            if(isset($options['form_field'])) {
                $obj_field_name = $options['form_field'];
            }
            $field_value = ($object) ? $accessor->getValue($object, $obj_field_name): null;

            $this->addDependantForm($form, $parent_id, $obj_field_name, $field_value, $options);
        }
    }

    public function preSubmit(FormEvent $event)
    {
        $data = $event->getData();
        $form = $event->getForm();

        foreach($this->fields as $name => $options) {
            $parent_field = $options['parent_entity_field'];
            if(isset($options['parent_form_field'])) {
                $parent_field = $options['parent_form_field'];
            }
            $parent_id = array_key_exists($parent_field, $data) ? $data[$parent_field] : null;

            $field_name = $options['entity_field'];
            if(isset($options['form_field'])) {
                $field_name = $options['form_field'];
            }
            $field_value = array_key_exists($field_name, $data) ? $data[$field_name] : null;

            $this->addDependantForm($form, $parent_id, $field_name, $field_value, $options);
        }
    }

    private function addDependantForm($form, $parent_id, $field_name, $field_value, $options)
    {
        $parent_property = $options['parent_entity_field'];
        #$field_name = $options['entity_field'];

        $order_field = null;
        $order_dir = 'ASC';
        $search_callback = null;
        if(array_key_exists('search_order_field', $options))
            $order_field = $options['search_order_field'];
        if(array_key_exists('search_order_direction', $options))
            $order_dir = $options['search_order_direction'];
        if(array_key_exists('search_callback', $options))
            $search_callback = $options['search_callback'];

        $filter_callback = null;
        //$doctrine_em = $this->container->get('doctrine');

        if (null !== $search_callback) {
            $filter_callback = $search_callback;
            //$repository = $doctrine_em->getRepository($options['class']);

            //if (!method_exists($repository, $filter_callback)) {
            //    $msg = 'Callback function "%s" in Repository "%s" does not exist. For class %s';
            //    $msg = sprintf($msg, $filter_callback,
            //                   get_class($repository), $options['class']);
            //    throw new \InvalidArgumentException($msg);
            //}
        }

        $query_builder = function (EntityRepository $repository)
        use ($parent_id, $parent_property,
             $order_dir, $order_field,
             $field_name, $field_value, $filter_callback) {

            $qb = null;

            if(null !== $filter_callback) {
                # Custom filtering, you must do all filtering
                $qb = $repository->$filter_callback($parent_id, $field_value);
            } else {
                # Default filter: filter by parent
                # if field_value is not null, include that value.
                $qb = $repository->createQueryBuilder('d')
                ->where('d.' . $parent_property . ' = :parent_id')
                ->setParameter('parent_id', $parent_id)
                ;
                if(null !== $field_value) {
                    $qb->orWhere('d = :field_value')
                    ->setParameter(':field_value', $field_value)
                    ;
                }

                if(null !== $order_field) {
                    $qb->addOrderBy('d.'.$order_field, $order_dir);
                }
            }
            return $qb;
             };

             $options['query_builder'] = $query_builder;

             $form->add($field_name, DependantEntityType::class, $options);
    }

    private function addCityForm(FormInterface $form, $provincia_id = null): void {

        $form->add('ciudad', DependantEntityType::class, [
            'form_field' => 'esta_te_doy',
            'class' => Ciudad::class,
            'placeholder' => '',
            'query_builder' => function (EntityRepository $repository) use ($provincia_id) {
                $qb = $repository->createQueryBuilder('ciudad')
                ->innerJoin('ciudad.provincia', 'provincia')
                ->where('provincia.id = :provincia')
                ->setParameter(':provincia', $provincia_id)
                ;

                return $qb;
            }
        ]);
    }

    public function preSetData2(FormEvent $event): void {
        $form = $event->getForm();
        #$conf = $form->getConfig()->getOptions();
        #echo print_r($conf['form_field']); die();
        // this would be your entity, i.e. SportMeetup
        $data = $event->getData();
        if (null === $data) {
            return;
        }
        # echo print_r($data), die();
        $city = $data->getCiudad();
        $province_id = ($city) ? $city->getProvincia()->getId() : null;
        $this->addCityForm($form, $province_id);
    }

    public function preSubmit2(FormEvent $event): void {
        //$form = $event->getForm();
        // It's important here to fetch $event->getForm()->getData(), as
        // $event->getData() will get you the client data (that is, the ID)
        //$mainobject = $form->getData();
        //$provincia = $mainobject->getProvincia();

        $data = $event->getData();
        $form = $event->getForm();
        $province_id = array_key_exists('provincia', $data) ? $data['provincia'] : null;
        $this->addCityForm($form, $province_id);
    }
}

src/Form/Model/Registro.php
<?php

namespace App\Form\Model;


class Registro
{
    protected ?string $email;
    protected ?string $nombre;
    protected ?string $apellido;
    protected ?string $nro_documento;
    protected ?string $sexo;

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(?string $nombre): void
    {
        $this->nombre = $nombre;
    }

    public function getApellido(): ?string
    {
        return $this->apellido;
    }

    public function setApellido(?string $apellido): void
    {
        $this->apellido = $apellido;
    }

    public function getNroDocumento(): ?int
    {
        return $this->nro_documento;
    }

    public function setNroDocumento(?int $nro_documento): void
    {
        $this->nro_documento = $nro_documento;
    }

    public function getSexo(): ?string
    {
        return $this->sexo;
    }

    public function setSexo(?string $sexo): void
    {
        $this->sexo = $sexo;
    }


}

src/Form/Type/AsientoSelectorType.php
<?php
namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;


class AsientoSelectorType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'x' => false,
        ]);

        # class option is required by base class
        $resolver->setRequired(array(
            'transporte', #
            'asientos_libres', # numeros de asientos libres
            'asientos_reserva',
            'idreserva',
        ));
    }

    public function getParent(): string
    {
        return TextType::class;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder->setAttribute("transporte", $options['transporte']);
        $builder->setAttribute("asientos_libres", $options['asientos_libres']);
        $builder->setAttribute("idreserva", $options['idreserva']);
        $builder->setAttribute("asientos_reserva", $options['asientos_reserva']);
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        parent::buildView($view, $form, $options);

        $view->vars['transporte'] = $form->getConfig()->getAttribute('transporte');
        $view->vars['idreserva'] = $form->getConfig()->getAttribute('idreserva');
        $view->vars['asientos_libres'] = $form->getConfig()->getAttribute('asientos_libres');
        $view->vars['asientos_reserva'] = $form->getConfig()->getAttribute('asientos_reserva');
    }
}

src/Form/Type/PasajeroType.php
<?php
namespace App\Form\Type;

use App\Entity\Pasajero;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PasajeroType extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options): void
{
    $builder
        ->add('nombre', TextType::class, [
            'label' => 'Nombre',
        ])
        ->add('apellido', TextType::class, [
            'label' => 'Apellido',
        ])
        ->add('dni', TextType::class, [
            'label' => 'DNI',
        ])
        ->add('sexo', ChoiceType::class, [
            'label' => 'Sexo',
            'choices' => [
                'Masculino' => 'M',
                'Femenino' => 'F',
                'Otro' => 'O',
            ],
            'placeholder' => 'Seleccione...', // Opcional, añade una opción vacía
            'expanded' => false, // false = dropdown, true = radio buttons
            'multiple' => false, // false = una selección, true = múltiples
        ]);
}

public function configureOptions(OptionsResolver $resolver): void
{
$resolver->setDefaults([
'data_class' => Pasajero::class,
]);
}
}

templates/form/asiento_selector_widget.html.twig
{% block asiento_selector_widget %}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
    {% set loaderid = [form.vars.id, '_loader'] | join('') %}
    {{ block('hidden_widget') }}
    <img src='{{ asset('bundles/applicationtools/images/ajax-loader.gif' ) }}' id='{{ loaderid }}' style='display: none;'>
    <script type="text/javascript">
        jQuery(function(){
            ;
        });
    </script>
    {% block styles %}
        <style>
            .btn-outline-secondary {
                color: #6c757d !important;
                border-color: #6c757d !important;
                background-color: transparent !important;
            }
            .btn-outline-secondary:hover {
                background-color: #6c757d !important; /* gris oscuro */
                color: #fff !important;
            }
        </style>
    {% endblock %}
{% set transporte=form.vars.transporte %}
{% set asientos_libres=form.vars.asientos_libres %}
{% set rows=transporte.grillaRows - 1 %}
{% set cols=transporte.grillaCols - 1 %}
{% set plantas=transporte.plantas - 1 %}

<div class="row">
{% for planta in 0 .. plantas %}
<div class="col-md-2">
    <table class="table table-bordered">
    <theader>
        <th colspan="{{ cols + 1 }}" style="text-align: center;">
            Frontal
        </th>
        {% if plantas > 0 %}
        <th colspan="{{ cols + 1 }}" style="text-align: center;">
        {{ transporte.plantaLabel(planta) }}
        </th>
        {% endif %}
    </theader>
    <tbody style="text-align: center;">
    {% for row in 0 .. rows %}
    <tr>
        {% for col in 0 .. cols %}
        <td>
        {% set asiento=transporte.getAsientoEnGrilla(planta, row, col) %}
        {% if asiento %}
            {% block celda_asiento %}
                {% if asiento.id in asientos_libres or asiento.id in asientos_reserva %}{# para ver asientos reservados pero en estado de espera #}

                    {% if asiento.id in asientos_reserva %}
                        {% if asiento.id not in asientos_libres %}{# es un asiento de mi reserva pero en estado WAIT (no esta libre) #}
                            {% set btn_class='btn btn-warning btn-lg' %}
                            <button class="{{ btn_class }}" type="submit" name="toggle_asiento" value="{{ asiento.id }}">{{ asiento.numero }}</button>
                        {% else %}
                            {% set btn_class='btn btn-primary btn-lg' %}
                            <button class="{{ btn_class }}" type="submit" name="toggle_asiento" value="{{ asiento.id }}">{{ asiento.numero }}</button>
                        {% endif %}
                    {% else %}
                        {% set btn_class='btn btn-outline-secondary btn-lg' %}
                        <a href="#" class="{{ btn_class }}" data-toggle="modal" data-target="#modal{{ asiento.id }}" onclick="procAsiento({{ form.vars.idreserva }},{{ asiento.id }},{{ asiento.numero }})">{{ asiento.numero }}</a>
                        {# form para carga de pasajero del boleto #}
                        <div class="modal fade" id="modal{{ asiento.id }}" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="createModalLabel"></h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body" id="f{{ asiento.id }}"></div>
                                </div>
                            </div>
                        </div>
                        <script type="text/javascript">
                            function procAsiento(idreserva,idasiento,asientonumero) {
                                $.ajax({
                                    url: '{{ path('admin_app_reserva_modalForm') }}',
                                    method: 'POST',
                                    processData: false,
                                    contentType: "application/json; charset=utf-8",
                                    data: JSON.stringify({ "idreserva": idreserva, "idasiento": idasiento, 'asientonumero': asientonumero}),
                                    dataType: "json",
                                    success: function (data) {
                                        console.log('AJAX Success:', data);
                                        $('#f'+idasiento).append().empty();
                                        $('#f'+idasiento).append(data);
                                    }
                                });
                            }
                        </script>

                    {% endif %}
                {% else %}
                    <div><img src='{{ asset('images/ocupado.png' ) }}' style="width: 40px; height: 40px"></div>
                {% endif %}
            {% endblock %}
        {% else %}
            {% block celda_vacia %}
                &nbsp;
            {% endblock %}
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
    </tbody>
    </table>
</div>
{% endfor %}
</div>



{% endblock %}
{# kate: tab-width 2 #}

templates/form/dependant_entity_widget.html.twig
{% block dependant_entity_widget %}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
    {{ block('choice_widget') }}
    {% set loaderid = [form.vars.id, '_loader'] | join('') %}
    {% if form.parent.offsetExists(parent_form_field) %}
      {% set parent_field_html_id = form.parent.offsetGet(parent_form_field).vars.id %}
    {% else %}
      {# support for admin filters: #}
      {% if form.parent.parent.offsetExists(parent_form_field) %}
        {% set parent_field_html_id = form.parent.parent.offsetGet(parent_form_field).offsetGet('value').vars.id %}
      {% else %}
        Filtros dependientes: Se encontro un estado inesperado en formato de plantilla.
      {% endif %}
    {% endif %}
    <img src='{{ asset('bundles/applicationtools/images/ajax-loader.gif' ) }}' id='{{ loaderid }}' style='display: none;'>
    <script type="text/javascript">
        jQuery(function(){

            jQuery("select#{{ parent_field_html_id }}").change( function() {
                var selected_index = {{ value ? value : 0 }};
                jQuery("#{{ loaderid }}").show();
                jQuery.ajax({
                    type: "POST",
                    data: {
                        parent_id: jQuery(this).val(),
                        config_name: "{{ config_name }}",
                        placeholder: "{{ placeholder }}",
                        origvalue: "{{ value }}"
                    },
                    url:"{{ path('app_dependant_entity_options') }}",
                    success: function(msg){
                        if (msg != ''){
                            jQuery("select#{{ form.vars.id }}").html(msg).show();
                            jQuery.each(jQuery("select#{{ form.vars.id }} option"), function (index, option){
                                if (jQuery(option).val() == selected_index)
                                    jQuery(option).prop('selected', true);
                            })
                            jQuery("select#{{ form.vars.id }}").trigger('change');
                            jQuery("#{{ loaderid }}").hide();
                        } else {
                            jQuery("select#{{ form.vars.id }}").html('<em>{{ no_result_msg|trans() }}</em>');
                            jQuery("#{{ loaderid }}").hide();
                        }
                    },
                    error: function(xhr, ajaxOptions, thrownError){
                    jQuery('html').html(xhr.responseText);
                    }
                });
            });
        });
    </script>
{% endblock %}
{# kate: tab-width 2 #}